# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2fa0d66c9f0d375dff612d1c16f6d6ad"
name = "fav-app-8"
handle = "fav-app-8"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_script_tags,write_customers,write_products,write_script_tags"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
